/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Convert a Lua data file to a JSON string. */
export declare function convertLuaFileToJson(path: string, opts?: ConvertOptions | undefined | null): string

/** Convert a Lua data string to a JSON string. */
export declare function convertLuaToJson(input: string, opts?: ConvertOptions | undefined | null): string

export interface ConvertOptions {
  emptyTable?: string
  arrayMode?: string
  arrayMaxGap?: number
  stringTransform?: StringTransformOptions
}

export interface StringTransformOptions {
  maxLen: number
  mode?: string
  replacement?: string
}
