name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: go.mod

      - name: Build
        run: go build ./...

      - name: Build WASM
        run: GOOS=js GOARCH=wasm go vet ./cmd/wasm

      - name: Test
        run: go test ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9.2.0
        with:
          version: v2.11.3

      - name: Validate testdata
        run: make validate-testdata
