name: Deploy to GitHub Pages

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: dtolnay/rust-toolchain@stable

      - uses: actions/setup-go@v6.3.0
        with:
          go-version-file: web/docs/gen/go.mod

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build site
        run: make build-site SITE_VERSION=${{ github.ref_name }}

      - uses: actions/upload-pages-artifact@v4
        with:
          path: bin/web

      - id: deployment
        uses: actions/deploy-pages@v4
